treasure_chest_base_address = 0xE03D80

class MemoryLocation():
    def __init__(self, address, bit, set_when_checked):
        self.address = address
        self.bit = bit
        self.set_when_checked = set_when_checked

treasure_chests = {
    "Mushroom Way 1", MemoryLocation(treasure_chest_base_address + 9, 6, False),
    "Mushroom Way 2", MemoryLocation(treasure_chest_base_address + 9, 7, False),
    "Mushroom Way 3", MemoryLocation(treasure_chest_base_address + 10, 0, False),
    "Mushroom Way 4", MemoryLocation(treasure_chest_base_address + 10, 1, False),
    "Mushroom Kingdom Vault 1", MemoryLocation(treasure_chest_base_address + 0, 3, False),
    "Mushroom Kingdom Vault 2", MemoryLocation(treasure_chest_base_address + 0, 5, False),
    "Mushroom Kingdom Vault 3", MemoryLocation(treasure_chest_base_address + 0, 4, False),
    "Bandit's Way 1", MemoryLocation(treasure_chest_base_address + 10, 3, False),
    "Bandit's Way 2", MemoryLocation(treasure_chest_base_address + 2, 0, False),
    "Bandit's Way Star Chest", MemoryLocation(treasure_chest_base_address + 2, 1, False),
    "Bandit's Way Dog Jump", MemoryLocation(treasure_chest_base_address + 2, 2, False),
    "Bandit's Way Croco", MemoryLocation(treasure_chest_base_address + 10, 2, False),
    "Kero Sewers Pandorite Room", MemoryLocation(treasure_chest_base_address + 1, 6, False),
    "Kero Sewers Star Chest", MemoryLocation(treasure_chest_base_address + 1, 5, False),
    "Kero Sewers Recovery Chest", MemoryLocation(treasure_chest_base_address + 15, 4, False),
    "Kero Sewers Cricket Chest", MemoryLocation(treasure_chest_base_address + 15, 5, False),
    "Rose Way Platform", MemoryLocation(treasure_chest_base_address + 2, 3, False),
    "Rose Town Store 1", MemoryLocation(treasure_chest_base_address + 3, 1, False),
    "Rose Town Store 2", MemoryLocation(treasure_chest_base_address + 3, 2, False),
    "Gardener Cloud 1", MemoryLocation(treasure_chest_base_address + 19, 7, False),
    "Gardener Cloud 2", MemoryLocation(treasure_chest_base_address + 20, 0, False),
    "Forest Maze 1", MemoryLocation(treasure_chest_base_address + 10, 4, False),
    "Forest Maze 2", MemoryLocation(treasure_chest_base_address + 10, 5, False),
    "Forest Maze Underground 1", MemoryLocation(treasure_chest_base_address + 13, 4, False),
    "Forest Maze Underground 2", MemoryLocation(treasure_chest_base_address + 13, 5, False),
    "Forest Maze Underground 3", MemoryLocation(treasure_chest_base_address + 13, 3, False),
    "Forest Maze Red Essence", MemoryLocation(treasure_chest_base_address + 10, 6, False),
    "Pipe Vault Slide 1", MemoryLocation(treasure_chest_base_address + 6, 0, False),
    "Pipe Vault Slide 2", MemoryLocation(treasure_chest_base_address + 5, 7, False),
    "Pipe Vault Slide 3", MemoryLocation(treasure_chest_base_address + 5, 6, False),
    "Pipe Vault Nippers 1", MemoryLocation(treasure_chest_base_address + 6, 1, False),
    "Pipe Vault Nippers 2", MemoryLocation(treasure_chest_base_address + 6, 2, False),
    "Yo'ster Isle Entrance", MemoryLocation(treasure_chest_base_address + 0, 6, False),
    "Moleville Mines Star Chest", MemoryLocation(treasure_chest_base_address + 15, 1, False),
    "Moleville Mines Coins", MemoryLocation(treasure_chest_base_address + 15, 0, False),
    "Moleville Mines Punchinello 1", MemoryLocation(treasure_chest_base_address + 15, 2, False),
    "Moleville Mines Punchinello 2", MemoryLocation(treasure_chest_base_address + 15, 3, False),
    "Booster Pass 1", MemoryLocation(treasure_chest_base_address + 4, 5, False),
    "Booster Pass 2", MemoryLocation(treasure_chest_base_address + 4, 6, False),
    "Booster Pass Secret 1", MemoryLocation(treasure_chest_base_address + 19, 2, False),
    "Booster Pass Secret 2", MemoryLocation(treasure_chest_base_address + 19, 3, False),
    "Booster Pass Secret 3", MemoryLocation(treasure_chest_base_address + 19, 4, False),
    "Booster Tower Spookum", MemoryLocation(treasure_chest_base_address + 9, 0, False),
    "Booster Tower Thwomp", MemoryLocation(treasure_chest_base_address + 1, 0, False),
    "Booster Tower Masher", MemoryLocation(treasure_chest_base_address + 9, 1, False),
    "Booster Tower Parachute", MemoryLocation(treasure_chest_base_address + 0, 7, False),
    "Booster Tower Zoom Shoes", MemoryLocation(treasure_chest_base_address + 1, 1, False),
    "Booster Tower Top 1", MemoryLocation(treasure_chest_base_address + 9, 5, False),
    "Booster Tower Top 2", MemoryLocation(treasure_chest_base_address + 9, 2, False),
    "Booster Tower Top 3", MemoryLocation(treasure_chest_base_address + 9, 4, False),
    "Marrymore Inn", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Sea Star Chest", MemoryLocation(treasure_chest_base_address + 6, 7, False),
    "Sea Save Room 1", MemoryLocation(treasure_chest_base_address + 6, 3, False),
    "Sea Save Room 2", MemoryLocation(treasure_chest_base_address + 6, 4, False),
    "Sea Save Room 3", MemoryLocation(treasure_chest_base_address + 6, 5, False),
    "Sea Save Room 4", MemoryLocation(treasure_chest_base_address + 6, 6, False),
    "Sunken Ship Rat Stairs", MemoryLocation(treasure_chest_base_address + 7, 7, False),
    "Sunken Ship Shop", MemoryLocation(treasure_chest_base_address + 8, 0, False),
    "Sunken Ship Coins 1", MemoryLocation(treasure_chest_base_address + 8, 1, False),
    "Sunken Ship Coins 2", MemoryLocation(treasure_chest_base_address + 8, 2, False),
    "Sunken Ship Clone Room", MemoryLocation(treasure_chest_base_address + 8, 3, False),
    "Sunken Ship Frog Coin Room", MemoryLocation(treasure_chest_base_address + 8, 4, False),
    "Sunken Ship Hidon Mushroom", MemoryLocation(treasure_chest_base_address + 8, 5, False),
    "Sunken Ship Safety Ring", MemoryLocation(treasure_chest_base_address + 8, 7, False),
    "Sunken Ship Bandana Reds", MemoryLocation(treasure_chest_base_address + 8, 7, False),
    "Land's End Red Essence", MemoryLocation(treasure_chest_base_address + 7, 0, False),
    "Land's End Chow Pit 1", MemoryLocation(treasure_chest_base_address + 7, 1, False),
    "Land's End Chow Pit 2", MemoryLocation(treasure_chest_base_address + 7, 2, False),
    "Land's End Bee Room", MemoryLocation(treasure_chest_base_address + 7, 3, False),
    "Land's End Secret 1", MemoryLocation(treasure_chest_base_address + 14, 7, False),
    "Land's End Secret 2", MemoryLocation(treasure_chest_base_address + 14, 6, False),
    "Land's End Shy Away", MemoryLocation(treasure_chest_base_address + 19, 1, False),
    "Land's End Star Chest 1", MemoryLocation(treasure_chest_base_address + 14, 3, False),
    "Land's End Star Chest 2", MemoryLocation(treasure_chest_base_address + 14, 1, False),
    "Land's End Star Chest 3", MemoryLocation(treasure_chest_base_address + 14, 2, False),
    "Belome Temple Fortune Teller", MemoryLocation(treasure_chest_base_address + 20, 1, False),
    "Belome Temple After Fortune 1", MemoryLocation(treasure_chest_base_address + 20, 2, False),
    "Belome Temple After Fortune 2", MemoryLocation(treasure_chest_base_address + 20, 3, False),
    "Belome Temple After Fortune 3", MemoryLocation(treasure_chest_base_address + 20, 5, False),
    "Belome Temple After Fortune 4", MemoryLocation(treasure_chest_base_address + 20, 4, False),
    "Belome Temple Before Belome 1", MemoryLocation(treasure_chest_base_address + 20, 7, False),
    "Belome Temple Before Belome 2", MemoryLocation(treasure_chest_base_address + 20, 6, False),
    "Belome Temple Before Belome 3", MemoryLocation(treasure_chest_base_address + 21, 0, False),
    "Monstro Town Entrance", MemoryLocation(treasure_chest_base_address + 14, 5, False),
    "Bean Valley 1", MemoryLocation(treasure_chest_base_address + 14, 0, False),
    "Bean Valley 2", MemoryLocation(treasure_chest_base_address + 13, 7, False),
    "Bean Valley Box Boy Room", MemoryLocation(treasure_chest_base_address + 17, 1, False),
    "Bean Valley Slot Room", MemoryLocation(treasure_chest_base_address + 17, 3, False),
    "Bean Valley Piranha Plants", MemoryLocation(treasure_chest_base_address + 13, 6, False),
    "Bean Valley Beanstalk", MemoryLocation(treasure_chest_base_address + 18, 5, False),
    "Bean Valley Cloud 1", MemoryLocation(treasure_chest_base_address + 18, 1, False),
    "Bean Valley Cloud 2", MemoryLocation(treasure_chest_base_address + 18, 2, False),
    "Bean Valley Fall 1", MemoryLocation(treasure_chest_base_address + 18, 3, False),
    "Bean Valley Fall 2", MemoryLocation(treasure_chest_base_address + 18, 4, False),
    "Nimbus Land Shop", MemoryLocation(treasure_chest_base_address + 17, 2, False),
    "Nimbus Castle Before Birdo 1", MemoryLocation(treasure_chest_base_address + 4, 7, False),
    "Nimbus Castle Before Birdo 2", MemoryLocation(treasure_chest_base_address + 5, 1, False),
    "Nimbus Castle Out of Bounds 1", MemoryLocation(treasure_chest_base_address + 19, 5, False),
    "Nimbus Castle Out of Bounds 2", MemoryLocation(treasure_chest_base_address + 19, 6, False),
    "Nimbus Castle Single Gold Bird", MemoryLocation(treasure_chest_base_address + 5, 0, False),
    "Nimbus Castle Star Chest", MemoryLocation(treasure_chest_base_address + 5, 4, False),
    "Nimbus Castle Star After Valentina", MemoryLocation(treasure_chest_base_address + 5, 5, False),
    "Barrel Volcano Secret 1", MemoryLocation(treasure_chest_base_address + 17, 6, False),
    "Barrel Volcano Secret 2", MemoryLocation(treasure_chest_base_address + 18, 7, False),
    "Barrel Volcano Before Star 1", MemoryLocation(treasure_chest_base_address + 15, 5, False),
    "Barrel Volcano Before Star 2", MemoryLocation(treasure_chest_base_address + 18, 7, False),
    "Barrel Volcano Star Room", MemoryLocation(treasure_chest_base_address + 19, 0, False),
    "Barrel Volcano Save Room 1", MemoryLocation(treasure_chest_base_address + 17, 6, False),
    "Barrel Volcano Save Room 2", MemoryLocation(treasure_chest_base_address + 17, 7, False),
    "Barrel Volcano Hinnopio", MemoryLocation(treasure_chest_base_address + 18, 0, False),
    "Bowser's Keep Dark Room", MemoryLocation(treasure_chest_base_address + 22, 2, False),
    "Bowser's Keep Croco Shop 1", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Bowser's Keep Croco Shop 2", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Bowser's Keep Invisible Bridge 1", MemoryLocation(treasure_chest_base_address + 15, 7, False),
    "Bowser's Keep Invisible Bridge 2", MemoryLocation(treasure_chest_base_address + 16, 0, False),
    "Bowser's Keep Invisible Bridge 3", MemoryLocation(treasure_chest_base_address + 16, 1, False),
    "Bowser's Keep Invisible Bridge 4", MemoryLocation(treasure_chest_base_address + 16, 2, False),
    "Bowser's Keep Moving Platforms 1", MemoryLocation(treasure_chest_base_address + 23, 7, False),
    "Bowser's Keep Moving Platforms 2", MemoryLocation(treasure_chest_base_address + 24, 0, False),
    "Bowser's Keep Moving Platforms 3", MemoryLocation(treasure_chest_base_address + 24, 1, False),
    "Bowser's Keep Moving Platforms 4", MemoryLocation(treasure_chest_base_address + 23, 6, False),
    "Bowser's Keep Rotating Platform 1", MemoryLocation(treasure_chest_base_address + 22, 3, False),
    "Bowser's Keep Rotating Platform 2", MemoryLocation(treasure_chest_base_address + 22, 6, False),
    "Bowser's Keep Rotating Platform 3", MemoryLocation(treasure_chest_base_address + 22, 4, False),
    "Bowser's Keep Rotating Platform 4", MemoryLocation(treasure_chest_base_address + 22, 7, False),
    "Bowser's Keep Rotating Platform 5", MemoryLocation(treasure_chest_base_address + 22, 5, False),
    "Bowser's Keep Rotating Platform 6", MemoryLocation(treasure_chest_base_address + 23, 0, False),
    "Bowser's Keep Door Reward 1", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Bowser's Keep Door Reward 2", MemoryLocation(treasure_chest_base_address + 7, 4, False),
    "Bowser's Keep Door Reward 3", MemoryLocation(treasure_chest_base_address + 21, 7, False),
    "Bowser's Keep Door Reward 4", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Bowser's Keep Door Reward 5", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Bowser's Keep Door Reward 6", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Factory Save Room", MemoryLocation(treasure_chest_base_address + 13, 1, False),
    "Factory Bolt Platforms", MemoryLocation(treasure_chest_base_address + 13, 2, False),
    "Factory Falling Axems", MemoryLocation(treasure_chest_base_address + 0, 0, False),
    "Factory Treasure Pit 1", MemoryLocation(treasure_chest_base_address + 21, 5, False),
    "Factory Treasure Pit 2", MemoryLocation(treasure_chest_base_address + 21, 3, False),
    "Factory Conveyor Platforms 1", MemoryLocation(treasure_chest_base_address + 24, 2, False),
    "Factory Conveyor Platforms 2", MemoryLocation(treasure_chest_base_address + 24, 3, False),
    "Factory Behind Snakes 1", MemoryLocation(treasure_chest_base_address + 21, 4, False),
    "Factory Behind Snakes 2", MemoryLocation(treasure_chest_base_address + 21, 6, False),
    "Mario's Bed", MemoryLocation(0x2DC0, 4, False),
    "Croco 1", MemoryLocation(0x304D, 3, False),
    "Rare Frog Coin Reward", MemoryLocation(0x3083, 4, False),
    "Melody Bay Song 1", MemoryLocation(0x3051, 4, False),
    "Melody Bay Song 2", MemoryLocation(0x3054, 5, False),
    "Melody Bay Song 3", MemoryLocation(0x3054, 6, False),
    "Rose Town Sign", MemoryLocation(0x2D68, 2, False),
    "Yo'ster Isle Goal", MemoryLocation(0x2D3A, 0, False),
    "Croco 2", MemoryLocation(0x3056, 5, False),
    "Booster Tower Ancestors", MemoryLocation(0x2DCB, 7, False),
    "Booster Tower Checkerboard", MemoryLocation(0x3054, 2, False),
    "Knife Guy", MemoryLocation(0x3099, 6, False),
    "Seaside Town Key", MemoryLocation(0x2E19, 3, False),
    "Monstro Town Key", MemoryLocation(0x3092, 7, False),
    "Nimbus Land Castle Key", MemoryLocation(0x305F, 6, False),
    "Birdo", MemoryLocation(0x305F, 5, False),
    "Fertilizer", MemoryLocation(0x2E6F, 5, False),
    "Toad Rescue 1", MemoryLocation(0x3052, 4, False),
    "Toad Rescue 2", MemoryLocation(0x3052, 5, False),
    "Hammer Bros Reward", MemoryLocation(0x3052, 6, False),
    "Wallet Guy 1", MemoryLocation(0x3083, 2, False),
    "Wallet Guy 2", MemoryLocation(0x3083, 2, False),
    "Mushroom Kingdom Store", MemoryLocation(0x3089, 6, False),
    "Peach Surprise", MemoryLocation(0x3084, 4, False),
    "Invasion Family", MemoryLocation(0x3082, 6, False),
    "Invasion Guest Room", MemoryLocation(0x3083, 0, False),
    "Invasion Guard", MemoryLocation(0x3082, 5, False),
    "Croco 1 Reward", MemoryLocation(0x3082, 5, False),
    "Pandorite Reward", MemoryLocation(0x3057, 5, False),
    "Midas River First Time", MemoryLocation(0x3043, 3, False),
    "Rose Town Toad", MemoryLocation(0x3084, 0, False),
    "Gaz", MemoryLocation(0x3085, 7, False),
    "Treasure Seller 1", MemoryLocation(0x3088, 1, False),
    "Treasure Seller 2", MemoryLocation(0x3088, 0, False),
    "Treasure Seller 3", MemoryLocation(0x3088, 2, False),
    "Croco Flunkie 1", MemoryLocation(0x3057, 0, False),
    "Croco Flunkie 2", MemoryLocation(0x3056, 3, False),
    "Croco Flunkie 3", MemoryLocation(0x3056, 6, False),
    "Booster Tower Railway", MemoryLocation(0x2DC6, 0, False),
    "Booster Tower Chomp", MemoryLocation(0x2DCB, 7, False),
    "Booster Tower Curtain Game", MemoryLocation(0x3053, 5, False),
    "Seaside Town Rescue", MemoryLocation(0x3086, 6, False),
    "Sunken Shio 3D Maze", MemoryLocation(0x307D, 2, False),
    "Sunken Shio Cannonball Puzzle", MemoryLocation(0x307D, 1, False),
    "Sunken Shio Hidon Reward", MemoryLocation(0x3057, 7, False),
    "Belome Temple Treasure 1", MemoryLocation(0x2E67, 5, False),
    "Belome Temple Treasure 2", MemoryLocation(0x2E67, 6, False),
    "Belome Temple Treasure 3", MemoryLocation(0x2E67, 7, False),
    "Jinx Dojo Reward", MemoryLocation(0x308A, 5, False),
    "Culex Reward", MemoryLocation(0x3093, 4, False),
    "Super Jumps 30", MemoryLocation(0x3092, 0, False),
    "Super Jumps 100", MemoryLocation(0x3092, 2, False),
    "Three Musty Fears", MemoryLocation(0x3089, 7, False),
    "Troopa Climb", MemoryLocation(0x3094, 7, False),
    "Dodo Reward", MemoryLocation(0x3093, 1, False),
    "Nimbus Land Inn", MemoryLocation(0x3098, 6, False),
    "Nimbus Land Prisoners", MemoryLocation(0x305F, 7, False),
    "Nimbus Land Signal Ring", MemoryLocation(0x3084, 3, False),
    "Nimbus Land Cellar", MemoryLocation(0x309F, 3, False),
    "Factory Toad Gift", MemoryLocation(0x3059, 5, False),
    "Goomba Thumping 1", MemoryLocation(0x3099, 4, False),
    "Goomba Thumping 2", MemoryLocation(0x3099, 5, False),
    "Cricket Pie Reward", MemoryLocation(0x3051, 2, False),
    "Cricket Jam Reward", MemoryLocation(0x3051, 3, False),
    "Hammer Bros", MemoryLocation(0x3052, 6, False),
    "Croco 1 (Boss)", MemoryLocation(0x304D, 3, False),
    "Mack", MemoryLocation(0x3082, 0, False),
    "Pandorite", MemoryLocation(0x3057, 5, False),
    "Belome 1", MemoryLocation(0x3055, 2, False),
    "Bowyer", MemoryLocation(0x3083, 6, False),
    "Croco 2 (Boss)", MemoryLocation(0x3056, 5, False),
    "Punchinello", MemoryLocation(0x3056, 3, False),
    "Booster", MemoryLocation(0x3053, 4, False),
    "Clown Bros", MemoryLocation(0x3048, 6, False),
    "Bundt", MemoryLocation(0x304C, 6, False),
    "Star Hill", MemoryLocation(0x308B, 5, False),
    "King Calamari", MemoryLocation(0x3058, 6, False),
    "Hidon", MemoryLocation(0x3057, 7, False),
    "Johnny", MemoryLocation(0x3058, 7, False),
    "Yaridovich", MemoryLocation(0x3086, 0, False),
    "Belome 2", MemoryLocation(0x307C, 5, False),
    "Jagger", MemoryLocation(0x308A, 2, False),
    "Jinx 1", MemoryLocation(0x308A, 3, False),
    "Jinx 2", MemoryLocation(0x308A, 4, False),
    "Jinx 3 (Boss)", MemoryLocation(0x308A, 5, False),
    "Culex", MemoryLocation(0x3093, 4, False),
    "Box Boy", MemoryLocation(0x3064, 6, False),
    "Mega Smilax", MemoryLocation(0x308C, 3, False),
    "Dodo", MemoryLocation(0x3092, 7, False),
    "Birdo (Boss)", MemoryLocation(0x305F, 5, False),
    "Valentina", MemoryLocation(0x304A, 2, False),
    "Czar Dragon", MemoryLocation(0x307E, 0, False),
    "Axem Rangers", MemoryLocation(0x307D, 7, False),
    "Magikoopa", MemoryLocation(0x3093, 6, False),
    "Boomer", MemoryLocation(0x3054, 2, False),
    "Exor", MemoryLocation(0x3093, 7, False),
    "Countdown", MemoryLocation(0x308F, 7, False),
    "Cloaker and Domino", MemoryLocation(0x3096, 0, False),
    "Clerk", MemoryLocation(0x3059, 4, False),
    "Manager", MemoryLocation(0x3091, 3, False),
    "Director", MemoryLocation(0x2E8E, 5, False),
    "Gunyolk", MemoryLocation(0x308F, 6, False),
    "Smithy", MemoryLocation(0x304A, 2, False),
}